### ISSUE TITLE
Redirect card "read more" links to our readthedocs documentation 

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/GSOD.Contributors_website#2]
**Describe how we are communicating and why it is not optimal.**
Currently the "read more" options on the cards are empty. It would be preferable if we can redirect them to our readthedocs documentation links for reference.

**Additional context**
Current card sections: - 

![image](https://user-images.githubusercontent.com/33183263/93980046-bebc6f80-fd9b-11ea-94b1-517031ec5643.png)

**Comment by shubhamkarande13** [comment]
Hey @Tlazypanda !
I am yet confused about which links to be added to the cards as we have multiple repositories on GitHub. 😅
Once the links are finalised I will add them and push! 😁

@Tlazypanda @gmajan @Patamap
