### ISSUE TITLE
Add form for slack invite

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/GSOD.Contributors_website#3]
**Describe how we are communicating and why it is not optimal.**
Since our slack is closed as of now, we propose adding a contact form in the contributors website that will enable contributors to fill the form that will be mailed to info@moja.global and then the maintainers can decide whether to invite them to slack or not.

**Additional context**
The button here should open the form as a popup. Additionally the text here would be changed to make it understandable for the contributor.
![image](https://user-images.githubusercontent.com/33183263/93980972-f5df5080-fd9c-11ea-8034-f6305e6fe941.png)

**Comment by shubhamkarande13** [comment]
We also need to decide how the email system will work and which email account will be used.
@gmajan @Patamap We would love to have your opinion on this!
